# Generated by Django 5.1.7 on 2025-03-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0005_alter_product_stock_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default='fsa', max_digits=20),
        ),
    ]
