# Generated by Django 5.1.7 on 2025-03-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0007_customer_sale_saleitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='POSSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Company', max_length=255)),
                ('address', models.CharField(default='Address Here', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
            ],
        ),
    ]
